// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DownloadHamlib() {
  return window['go']['main']['App']['DownloadHamlib']();
}

export function GetCertInfo() {
  return window['go']['main']['App']['GetCertInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHamlibStatus() {
  return window['go']['main']['App']['GetHamlibStatus']();
}

export function GetRotatorStatus() {
  return window['go']['main']['App']['GetRotatorStatus']();
}

export function GetSerialPorts() {
  return window['go']['main']['App']['GetSerialPorts']();
}

export function GetStations(arg1, arg2) {
  return window['go']['main']['App']['GetStations'](arg1, arg2);
}

export function GetUDPStatus() {
  return window['go']['main']['App']['GetUDPStatus']();
}

export function InstallCert() {
  return window['go']['main']['App']['InstallCert']();
}

export function IsCertInstalled() {
  return window['go']['main']['App']['IsCertInstalled']();
}

export function RadioSetFreq(arg1) {
  return window['go']['main']['App']['RadioSetFreq'](arg1);
}

export function RadioSetTxFreq(arg1) {
  return window['go']['main']['App']['RadioSetTxFreq'](arg1);
}

export function RefreshRadioModels() {
  return window['go']['main']['App']['RefreshRadioModels']();
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function RotatorGoto(arg1, arg2) {
  return window['go']['main']['App']['RotatorGoto'](arg1, arg2);
}

export function RotatorPark() {
  return window['go']['main']['App']['RotatorPark']();
}

export function RotatorSetFollow(arg1) {
  return window['go']['main']['App']['RotatorSetFollow'](arg1);
}

export function SaveAdvanced(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAdvanced'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchRadioModels(arg1) {
  return window['go']['main']['App']['SearchRadioModels'](arg1);
}

export function StartHamlib() {
  return window['go']['main']['App']['StartHamlib']();
}

export function StopHamlib() {
  return window['go']['main']['App']['StopHamlib']();
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function TestWavelog(arg1) {
  return window['go']['main']['App']['TestWavelog'](arg1);
}
