// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {cert} from '../models';
import {config} from '../models';
import {wavelog} from '../models';
import {hamlib} from '../models';

export function CreateProfile(arg1:string):Promise<number>;

export function DeleteProfile(arg1:number):Promise<void>;

export function DownloadHamlib():Promise<main.DownloadResult>;

export function GetCertInfo():Promise<cert.Info>;

export function GetConfig():Promise<config.Config>;

export function GetHamlibStatus():Promise<main.HamlibStatus>;

export function GetRotatorStatus():Promise<main.RotatorStatus>;

export function GetSerialPorts():Promise<Array<string>>;

export function GetStations(arg1:string,arg2:string):Promise<Array<wavelog.Station>>;

export function GetUDPStatus():Promise<main.UDPStatus>;

export function InstallCert():Promise<cert.InstallResult>;

export function IsCertInstalled():Promise<boolean>;

export function RadioSetFreq(arg1:number):Promise<void>;

export function RadioSetTxFreq(arg1:number):Promise<void>;

export function RefreshRadioModels():Promise<number>;

export function RenameProfile(arg1:number,arg2:string):Promise<void>;

export function RotatorGoto(arg1:number,arg2:number):Promise<void>;

export function RotatorPark():Promise<void>;

export function RotatorSetFollow(arg1:string):Promise<void>;

export function SaveAdvanced(arg1:boolean,arg2:number,arg3:boolean):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<config.Config>;

export function SearchRadioModels(arg1:string):Promise<Array<hamlib.RadioModel>>;

export function StartHamlib():Promise<void>;

export function StopHamlib():Promise<void>;

export function SwitchProfile(arg1:number):Promise<void>;

export function TestWavelog(arg1:config.Profile):Promise<main.TestResult>;
